# Generated by Django 4.2.30 on 2026-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagem', models.ImageField(null=True, upload_to='imagens/', verbose_name='Imagem')),
                ('descricao', models.TextField(null=True, verbose_name='descrição')),
            ],
        ),
    ]
